### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by bragovo** [bragovo/fast-rocket-app#4]
- [x] Reload rooms list after someone add user (https://github.com/bragovo/fast-rocket-app/pull/5)
- [ ] Add user selection to Slate
- [ ] Add direct messages
- [ ] Check messages content (images, rich format etc.)
- [ ] Rooms list scroll
- [ ] Add events listener for messages in Store
